import json
import os
from datetime import datetime
try:
    from fpdf import FPDF
    FPDF_AVAILABLE = True
except Exception:
    FPDF_AVAILABLE = False
from src.core.database import EvidenceVault

class ForensicReportGenerator:
    """
    Generates Court-Admissible PDF Reports with Cryptographic Chain of Custody.
    """
    def __init__(self, vault: EvidenceVault):
        self.vault = vault

    def generate_pdf(self, case_id: str, output_path: str) -> dict:
        if not FPDF_AVAILABLE:
            return {"status": "ERROR", "message": "PDF engine unavailable on this device"}
        # 1. Fetch and Verify Cryptographic Chain
        chain_data = self.vault.get_case_chain(case_id)
        if not chain_data:
            return {"status": "ERROR", "message": "No evidence chain found for this case."}
            
        is_valid = True
        prev_hash = "GENESIS"
        for raw_json, db_prev, db_curr, db_sig in chain_data:
            if db_prev != prev_hash:
                is_valid = False
                break
            data_dict = json.loads(raw_json)
            if not self.vault.seal.verify(data_dict, db_prev, db_curr, db_sig):
                is_valid = False
                break
            prev_hash = db_curr
            
        # 2. Initialize PDF Document
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, "PROJECT NETRA-CORE: FORENSIC INVESTIGATION REPORT", ln=True, align="C")
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 8, "CLASSIFICATION: RESTRICTED / LAW ENFORCEMENT ONLY", ln=True, align="C")
        pdf.cell(0, 8, f"Case ID: {case_id}", ln=True, align="C")
        pdf.cell(0, 8, f"Generated At: {datetime.utcnow().isoformat()}Z", ln=True, align="C")
        pdf.ln(10)
        
        # Chain of Custody Status
        pdf.set_font("Helvetica", "B", 12)
        if is_valid:
            pdf.set_text_color(0, 128, 0)
            status_text = "INTACT (COURT ADMISSIBLE)"
        else:
            pdf.set_text_color(255, 0, 0)
            status_text = "TAMPERED (REJECTED BY COURT)"
            
        pdf.cell(0, 10, f"Chain of Custody Status: {status_text}", ln=True)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(5)
        
        # Executive Summary of Findings
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "EXECUTIVE SUMMARY OF FINDINGS", ln=True)
        pdf.set_font("Helvetica", "", 10)
        
        findings = self.vault.get_case_findings(case_id)
        for f in findings:
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 8, f"[{f.get('severity')}] {f.get('module')}: {f.get('title')}", ln=True)
            pdf.set_font("Helvetica", "", 9)
            pdf.multi_cell(0, 5, f"Description: {f.get('description')}")
            pdf.ln(3)
            
        # Cryptographic Appendix (For Technical Verification)
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "CRYPTOGRAPHIC APPENDIX (HMAC-SHA256)", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 5, "The following hashes prove the mathematical integrity of the evidence. Any alteration in the database will invalidate these signatures.")
        pdf.ln(5)
        
        pdf.set_font("Courier", "", 8)
        for raw_json, db_prev, db_curr, db_sig in chain_data:
            data = json.loads(raw_json)
            pdf.cell(0, 5, f"Record ID : {data.get('finding_id')}", ln=True)
            pdf.cell(0, 5, f"Prev_Hash : {db_prev[:48]}...", ln=True)
            pdf.cell(0, 5, f"Curr_Hash : {db_curr[:48]}...", ln=True)
            pdf.cell(0, 5, f"Signature : {db_sig[:48]}...", ln=True)
            pdf.ln(3)
            
        # Footer Signature
        pdf.ln(10)
        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(0, 5, "This document is system-generated by Project Netra-Core Forensic Engine.", ln=True, align="C")
        pdf.cell(0, 5, "Requires authorized human legal review for final court submission.", ln=True, align="C")
            
        # Save PDF
        pdf.output(output_path)
        return {"status": "SUCCESS", "path": output_path, "records": len(chain_data), "is_valid": is_valid}

# Patch: Add digital signature to PDF
class ForensicReportGeneratorSigned(ForensicReportGenerator):
    """Extends base generator with RSA-4096 digital signatures."""

    def __init__(self, vault):
        super().__init__(vault)
        from src.core.pdf_signer import PDFSigner
        self.signer = PDFSigner()

    def generate_signed_pdf(self, case_id: str, output_path: str) -> dict:
        # 1. Generate base PDF
        base_result = self.generate_pdf(case_id, output_path)
        if base_result["status"] == "ERROR":
            return base_result

        # 2. Sign the PDF
        sig_meta = self.signer.sign_document(output_path)

        # 3. Write signature sidecar file
        sidecar_path = output_path + ".sig"
        import json
        with open(sidecar_path, "w") as f:
            json.dump(sig_meta, f, indent=2)

        base_result["signature"] = sig_meta
        base_result["signature_sidecar"] = sidecar_path
        return base_result
